steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'deploy spring app'
  entrypoint: 'bash'
  args:  ['app', 'deploy', '--project', '${PROJECT_ID}', 'app.yaml', '--quiet', '--version', '${SHORT_SHA}']
  dir: spring/

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'deploy portfolio app'
  entrypoint: 'bash'
  args: ['app', 'deploy', '--project', '${PROJECT_ID}', 'app.yaml', '--quiet', '--version', '${SHORT_SHA}']
  dir: portfolio/
  
timeout: '1600s'

options:
 logging: CLOUD_LOGGING_ONLY