steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:  ['app', 'deploy', '--project', '${PROJECT_ID}', 'app.yaml', '--quiet', '--version', '${SHORT_SHA}']
  dir: spring/

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['app', 'deploy', '--project', '${PROJECT_ID}', 'app.yaml', '--quiet', '--version', '${SHORT_SHA}']
  dir: portfolio/
  
timeout: '1600s'

options:
 logging: CLOUD_LOGGING_ONLY