steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'deploy spring app'
  args: ['app', 'deploy', '--project', '${PROJECT_ID}', 'app.yaml', 'dispatch.yaml', '--quiet', '--version', '${SHORT_SHA}']
  dir: spring/

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'deploy webapp app'
  args: ['app', 'deploy', '--project', '${PROJECT_ID}', 'app.yaml', 'dispatch.yaml', '--quiet', '--version', '${SHORT_SHA}']
  dir: webapp/
  
timeout: '1600s'

options:
 logging: CLOUD_LOGGING_ONLY