steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'deploy spring app'
  entrypoint: 'bash'
  #args: ['-c', 'gcloud app deploy --project=${PROJECT_ID} --version ${SHORT_SHA}']
  args: ['app', 'deploy', '--project', '${PROJECT_ID}', 'app.yaml', 'dispatch.yaml', '--quiet', '--version', '${SHORT_SHA}']
  dir: spring/

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'deploy webapp app'
  entrypoint: 'bash'
  #args: ['-c', 'gcloud app deploy --project=${PROJECT_ID} --version ${SHORT_SHA}']
  args: ['app', 'deploy', '--project', '${PROJECT_ID}', 'app.yaml', 'dispatch.yaml', '--quiet', '--version', '${SHORT_SHA}']
  dir: webapp/
  
timeout: '1600s'

options:
 logging: CLOUD_LOGGING_ONLY