steps:
  - id: "delete stale app engine versions for spring application"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
    - '-c'
    - |-
      echo "delete stale app engine versions for spring application"
      SPRING=$(gcloud app versions list --format="value(version.id)" --sort-by="~version.createTime" --service="spring-app" | awk "FNR > 2 {print $1}")
      echo "$$SPRING"
      for spring in ${SPRING[@]};
      do
        echo "${spring}"
        gcloud app versions delete --service="spring-app" "${spring}" --quiet
      done

  - id: "delete stale app engine versions for webapp application"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
    - '-c'
    - |-
      echo "delete stale app engine versions for webapp application"
      WEBAPP=$(gcloud app versions list --format="value(version.id)" --sort-by="~version.createTime" --service="webapp" | awk "FNR > 2 {print $1}")
      echo "$$WEBAPP"
      for webapp in ${WEBAPP[@]};
      do
        echo "${webapp}"
        gcloud app versions delete --service="webapp" "${webapp}" --quiet
      done

substitutions:
  _SERVER_ENV: dev

timeout: '1600s'

options:
 logging: CLOUD_LOGGING_ONLY