runtime: python27

env: standard
network:
  name: default
  subnetwork_name: default
  session_affinity: true

service: spring-app
api_version: 1
threadsafe: true


automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 5

handlers:
  - url: /static
    static_dir: static/


vpc_access_connector:
  name: projects/$PROJECT_ID/locations/us-cemtral1/connectors/app-engine-vpc-connector


