runtime: python27
env: standard
service: spring-app
api_version: 1
threadsafe: true

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /
  static_dir: spring

vpc_access_connector:
  name: projects/starry-axis-344217/locations/us-central1/connectors/app-engine-vpc-connector



